name: deploy-page

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          npm install -g @angular/cli@latest
          npm install
          ng deploy --base-href=/cv/
